### ISSUE TITLE
Release with support for Django 2.1

### ISSUE THREAD

**Issue by joshua-s** [jazzband/django-configurations#203] opened 2018-08-01 20:19 UTC
This package breaks on Django 2.1 due to a Django API change. I reproduced this issue using both the PyPi version and the master branch.

Here is the error I receive:
```
Traceback (most recent call last):
web_1       |   File "./manage.py", line 10, in <module>
web_1       |     from configurations.management import execute_from_command_line
web_1       |   File "/usr/local/lib/python3.7/site-packages/configurations/management.py", line 3, in <module>
web_1       |     importer.install(check_options=True)
web_1       |   File "/usr/local/lib/python3.7/site-packages/configurations/importer.py", line 49, in install
web_1       |     importer = ConfigurationImporter(check_options=check_options)
web_1       |   File "/usr/local/lib/python3.7/site-packages/configurations/importer.py", line 67, in __init__
web_1       |     self.check_options()
web_1       |   File "/usr/local/lib/python3.7/site-packages/configurations/importer.py", line 87, in check_options
web_1       |     add_help=False)
web_1       | TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by blueyed** [comment] 2018-08-01 21:49
Looks like it should be fixed in https://github.com/jazzband/django-configurations/pull/201/commits/d3b9931d3411cfabd1b03b02f4dc12f9f61f2d6a.

**Comment by bryson** [comment] 2018-08-02 17:33
When will a new PyPI release be created that includes this?

**Comment by blueyed** [comment] 2018-08-02 18:35
See also #195 (for 2.0, which worked for me so far).

I've merged https://github.com/jazzband/django-configurations/pull/201 already.

Somebody writing the changelog would help certainly.

**Comment by blueyed** [comment] 2018-08-03 11:43
Also confirmation that master actually works for you with dj21 would be helpful, too.

**Comment by moorchegue** [comment] 2018-08-08 06:00
I've tried 2.1 with current master and can confirm that the problem is gone.

**Comment by drewbrew** [comment] 2018-08-16 13:17
@blueyed cherry-picked my commit from #206 and tagged the new release. As soon as 2.1 goes live on PyPI, this should be good to be closed.

**Comment by blueyed** [comment] 2018-08-16 13:32
Released it now.
Thanks for the changelog, @drewbrew!

**Closed by blueyed** 2018-08-16 13:32 UTC
Labels: bug

**Comment by drewbrew** [comment] 2018-08-16 13:34
Glad to help. I'll be using this code in my example project in my DRF talk during DjangoCon US 2018, so I figured I might as well make sure all my dependencies are as up to date as possible. :D
